//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class library_DBEntities : DbContext
    {
        public library_DBEntities()
            : base("name=library_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Table_Amanat> Table_Amanat { get; set; }
        public virtual DbSet<Table_Book> Table_Book { get; set; }
        public virtual DbSet<Table_Member> Table_Member { get; set; }
        public virtual DbSet<Table_Users> Table_Users { get; set; }
        public virtual DbSet<Table_Category> Table_Category { get; set; }
        public virtual DbSet<Table_Vaziyat> Table_Vaziyat { get; set; }
    }
}
