//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Book
    {
        public int Id { get; set; }
        public string Onvan { get; set; }
        public string Nevisande { get; set; }
        public string Nasher { get; set; }
        public string Category { get; set; }
        public Nullable<System.DateTime> SaleNashr { get; set; }
        public Nullable<int> NobatCahp { get; set; }
        public Nullable<int> Tedad { get; set; }
    }
}
