//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table_Member
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Family { get; set; }
        public string Jensiyat { get; set; }
        public string Father_sName { get; set; }
        public string CodeMeli { get; set; }
        public System.DateTime TarikhOzviat { get; set; }
        public System.DateTime TarikhTavalod { get; set; }
        public string MahaleTavalod { get; set; }
        public string MadrakeTahsili { get; set; }
        public string TelephoneNumber { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
    }
}
